import Link from "next/link";

export function Landing() {
  return <main className="noctra-landing">
    <header className="landing-nav"><Link className="landing-mark" href="/"><span className="brand-sigil" aria-hidden="true"/><span className="brand-name">PIXAGENT</span></Link><nav><a href="#system">System</a><a href="#workflow">Workflow</a><Link className="nav-workspace" href="/workspace">Workspace <span>↗</span></Link></nav></header>
    <section className="landing-hero">
      <div className="hero-copy"><p className="landing-kicker"><span>✦</span> OBSERVABLE AI SOFTWARE STUDIO <b>·</b> 2026</p><h1>PIX<br/><em>AGENT</em><br/>FACTORY</h1><p className="landing-lede">A pixel operations system for directing your coding agents with scoped work, visible evidence, and human approval gates.</p><div className="terminal-readout"><span className="readout-pip"/><span>STUDIO ONLINE</span><i/><span>04 WORKERS READY</span></div><div className="hero-actions"><Link className="workspace-link" href="/workspace"><span className="button-label">Go to Agent Workspace</span><span className="button-arrow">→</span></Link><a className="text-link" href="#workflow">Explore the system <span>↓</span></a></div></div>
      <div className="hero-world" aria-hidden="true"><div className="office-frame"><div className="office-scene"/><div className="office-hud"><span><i/> LIVE STUDIO</span><b>06 DESKS</b><em>↗</em></div></div></div>
    </section>
    <section className="landing-marquee"><span>SCOPED TASKS</span><i>✦</i><span>VISIBLE QUEUES</span><i>✦</i><span>HUMAN GATES</span><i>✦</i><span>REAL AGENT SESSIONS</span></section>
    <section id="system" className="landing-grid"><article><div className="card-top"><p>01 / OBSERVE</p><b>◫</b></div><h2>See the work,<br/>not just the workers.</h2><span>Every task holds its owner, blocker, evidence, next decision and execution environment.</span><div className="card-pixels"/></article><article><div className="card-top"><p>02 / ORCHESTRATE</p><b>⌘</b></div><h2>Scope tools<br/>before dispatch.</h2><span>Distinct capabilities keep concurrent agents from inventing dependencies or colliding in the same workspace.</span><div className="card-pixels"/></article><article><div className="card-top"><p>03 / DECIDE</p><b>◆</b></div><h2>Keep the human<br/>at the controls.</h2><span>Reviews, approvals and verification requests arrive with the context needed to make a call.</span><div className="card-pixels"/></article></section>
    <section id="workflow" className="landing-workflow"><p className="landing-kicker">HOW THE FACTORY RUNS</p><div className="workflow-line"><span>BRIEF</span><i>→</i><span>SCOPED PLAN</span><i>→</i><span>PARALLEL BUILD</span><i>→</i><span>PROOF</span><i>→</i><span>DECISION</span></div><Link className="workspace-link inverse" href="/workspace"><span className="button-label">Enter the factory</span><span className="button-arrow">→</span></Link></section>
    <footer>PIXAGENT FACTORY <span>YOUR AI SOFTWARE STUDIO</span><span>BUILT FOR OBSERVABLE WORK</span></footer>
  </main>;
}
